site_name: gmalg 用户指南
site_url: "https://gmalg.readthedocs.io/zh-cn/latest/"
site_author: ww-rm
site_description: "gmalg 用户指南"

repo_url: https://github.com/ww-rm/gmalg/

edit_uri: blob/main/docs/

theme:
  name: readthedocs
  locale: zh_CN

nav:
  - "主页": "index.md"
  - "quickstart.md"
  - "api.md"

markdown_extensions:
  - toc:
      permalink: true

plugins:
  - search:
      lang: zh
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            show_root_full_path: true
            show_root_members_full_path: true
            show_object_full_path: true
            show_source: false
            merge_init_into_class: true
            members_order: source

            docstring_options:
              ignore_init_summary: true
              returns_named_value: false
