site_name: gmalg 中文文档
site_url: "https://gmalg.readthedocs.io/zh-cn/latest/"
site_author: ww-rm
site_description: "gmalg 中文文档"

repo_url: https://github.com/ww-rm/gmalg/

edit_uri: blob/main/docs/

theme:
  name: readthedocs
  locale: zh_CN

nav:
  - "主页": "index.md"
  - "quickstart.md"
  - "api-reference.md"

markdown_extensions:
  - toc:
      permalink: true

plugins:
  - search:
      lang: ja
